Np 9319 pdf thumbnails
BIBSYSDEV/dlr-nva-thumbnailer pull request #11
Opened 2022-09-19 12:53 UTC by anetteOlli

2022-09-19 14:32 UTC, ketilaa requested changes

2022-09-19 14:32 UTC, ketilaa commented on thumbnail-service/src/main/java/no/sikt/nva/thumbnail/thumbnailer/PdfThumbnailer.java
> +    private PDDocument document;
Don't use class field variables for storage between method calls. `document` should be instantiated  and returned in loadPDF, and sent as parameters to methods that need it. As a rule of thumb, class fields should be set in constructor.

2022-09-20 11:42 UTC, anetteOlli commented on thumbnail-service/src/main/java/no/sikt/nva/thumbnail/thumbnailer/PdfThumbnailer.java
> +    private PDDocument document;
Fikset

2022-09-20 11:58 UTC, ketilaa approved these changes

2022-09-20 14:31 UTC, merged